{{- if and .Values.execution.dind.enabled .Values.execution.dind.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shipsec-dind-pvc
  namespace: {{ .Values.global.namespaces.workloads }}
  labels:
    {{- include "shipsec.labels" . | nindent 4 }}
    app.kubernetes.io/component: dind
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.execution.dind.storage.size }}
{{- end }}

