# Managed services â€” disabled (Cloud SQL, Memorystore)
postgres:
  enabled: false

redis:
  enabled: false

# Still runs in-cluster
minio:
  enabled: true

temporal:
  enabled: true
  postgresHost: '10.25.225.3'
  postgresUser: shipsec
  postgresPassword: shipsec-dev-2026

redpanda:
  enabled: true

loki:
  enabled: true
